---
# .github/workflows/ansible-lint.yml
name: Ansible Lint

on:
  # Triggers the workflow on pull requests but only for the main branch
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".devcontainer/*"
      - ".editorconfig"
      - ".github/*"
      - ".gitignore"
      - ".vale.ini"
      - ".vscode/*"
      - "*/README.md"
      - "CHANGELOG.*"
      - "CODE_OF_CONDUCT.md"
      - "codecov.yml"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "MAINTAINERS"
      - "README.md"
      - "REVIEW_CHECKLIST.md"
      - "roles/.gitignore"
      - "roles/README.md"

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Run ansible-lint
        uses: ansible/ansible-lint@a2bc8b8b13a80802215856c56823d85007d3baf5 # v25 # or version tag instead of 'main'
